apiVersion: v2
name: topology-discovery
description: A Helm chart for Kubernetes deployment of the Topology Discovery
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 4.0.0
appVersion: "7.0.0"
maintainers:
  - name: FRINX
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Compatible with 7.0.0 release. Environment variable changes
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/TODO
