apiVersion: v2
name: worker
version: 4.0.0
appVersion: "6.0.0"
description: A Helm chart for conductor workers
type: application
home: https://github.com/FRINXio/helm-charts
maintainers:
  - name: FRINX
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Changed env variables compatible with Frinx Machine 6.0.0
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/376
